version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - backend_build:
          filters:
            branches:
              only: main
      - frontend_build:
          filters:
            branches:
              only: main

jobs:
  backend_build:
    machine:
      image: ubuntu-2204:2023.04.2
    working_directory: ~/project/PackYourBags_Backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Verify Docker
          command: docker info
      - run:
          name: Build and test backend
          command: mvn -B clean package

  frontend_build:
    docker:
      - image: cimg/node:20.0
    working_directory: ~/project/PackYourBags_Frontend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install frontend dependencies
          command: npm install
      - run:
           name: Run frontend tests
           command: npm test -- --pool=threads --threads=false
      - run:
          name: Build frontend
          command: npm run build
