version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - backend_build:
          filters:
            branches:
              only: main
      - frontend_build:
          filters:
            branches:
              only: main

jobs:
  backend_build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project/PackYourBags_Backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build Spring Boot backend
          command: mvn -B clean package

  frontend_build:
    docker:
      - image: cimg/node:21.0
    working_directory: ~/project/PackYourBags_Frontend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install frontend dependencies
          command: npm install
      # - run:
      #     name: Run frontend tests
      #     command: npm test
      - run:
          name: Build frontend
          command: npm run build
